spring:
  zipkin:
    base-url: http://127.0.0.1:8004/ 

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9090/eureka/
  instance:
    hostname: localhost 
 
